version: '3'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/optics
      - SPRING_DATASOURCE_USERNAME=Admin
      - SPRING_DATASOURCE_PASSWORD=1234

  db:
    image: 'postgres:14-alpine3.14'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=optics
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=Admin