CREATE TABLE IF NOT EXISTS GLASSES_CONSTRUCTORS(
	Id CHARACTER(20) NOT NULL PRIMARY KEY,
	Frame_Id CHARACTER(20) NOT NULL,
	OD_Lens_Id CHARACTER(20) NOT NULL,
	OD_Angle CHARACTER(3),
	OS_Lens_Id CHARACTER(20) NOT NULL,
	OS_Angle CHARACTER(3),
	Distance CHARACTER(3) NOT NULL,
	Work_Price CHARACTER(10) NOT NULL,
	Amount CHARACTER(3) NOT NULL,
	Total_Price CHARACTER(10) NOT NULL
)

	TABLESPACE pg_default;

	ALTER TABLE IF EXISTS GLASSES_CONSTRUCTORS 
		OWNER TO "Admin";