CREATE TABLE IF NOT EXISTS ORDERS (
	Id CHARACTER(40) PRIMARY KEY,
	Customer_Id CHARACTER(20) REFERENCES CUSTOMERS(Id),
    Address CHARACTER(200),
	Created CHARACTER(18),
	Updated CHARACTER(18),
	Status CHARACTER(11)
)

	TABLESPACE pg_default;

	ALTER TABLE IF EXISTS ORDERS 
		OWNER TO "Admin";


CREATE TABLE IF NOT EXISTS ORDER_LINES (

    Id CHARACTER(40) PRIMARY KEY,
	Order_Id CHARACTER(40),
	Product_Id CHARACTER(20),
	Quantity CHARACTER(20),
	Price CHARACTER(20)
)

	TABLESPACE pg_default;

	ALTER TABLE IF EXISTS ORDER_LINES 
		OWNER TO "Admin";


CREATE TABLE IF NOT EXISTS CONSTRUCTORS_ORDER_LINES (

    Id CHARACTER(40) PRIMARY KEY,
	Order_Id CHARACTER(40),
	Constructor_Id CHARACTER(20),
	Quantity CHARACTER(20),
	Price CHARACTER(20)
)

	TABLESPACE pg_default;

	ALTER TABLE IF EXISTS CONSTRUCTORS_ORDER_LINES
		OWNER TO "Admin";
